/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DecomInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptBid"
      | "bounties"
      | "cancelBounty"
      | "createBounty"
      | "submitResult"
      | "verifyAndRelease"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BidAccepted"
      | "BountyCancelled"
      | "BountyCompleted"
      | "BountyCreated"
      | "ResultSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptBid",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bounties",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelBounty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBounty",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResult",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAndRelease",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "acceptBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bounties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndRelease",
    data: BytesLike
  ): Result;
}

export namespace BidAcceptedEvent {
  export type InputTuple = [id: BigNumberish, worker: AddressLike];
  export type OutputTuple = [id: bigint, worker: string];
  export interface OutputObject {
    id: bigint;
    worker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyCancelledEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyCompletedEvent {
  export type InputTuple = [
    id: BigNumberish,
    worker: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: bigint, worker: string, amount: bigint];
  export interface OutputObject {
    id: bigint;
    worker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    creator: AddressLike,
    amount: BigNumberish,
    ipfsCid: string
  ];
  export type OutputTuple = [
    id: bigint,
    creator: string,
    amount: bigint,
    ipfsCid: string
  ];
  export interface OutputObject {
    id: bigint;
    creator: string;
    amount: bigint;
    ipfsCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultSubmittedEvent {
  export type InputTuple = [id: BigNumberish, resultHash: string];
  export type OutputTuple = [id: bigint, resultHash: string];
  export interface OutputObject {
    id: bigint;
    resultHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Decom extends BaseContract {
  connect(runner?: ContractRunner | null): Decom;
  waitForDeployment(): Promise<this>;

  interface: DecomInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptBid: TypedContractMethod<
    [bountyId: BigNumberish, worker: AddressLike],
    [void],
    "nonpayable"
  >;

  bounties: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, string, string] & {
        id: bigint;
        creator: string;
        ipfsCid: string;
        amount: bigint;
        status: bigint;
        assignedWorker: string;
        resultHash: string;
      }
    ],
    "view"
  >;

  cancelBounty: TypedContractMethod<
    [bountyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createBounty: TypedContractMethod<[ipfsCid: string], [void], "payable">;

  submitResult: TypedContractMethod<
    [bountyId: BigNumberish, resultHash: string],
    [void],
    "nonpayable"
  >;

  verifyAndRelease: TypedContractMethod<
    [bountyId: BigNumberish, success: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptBid"
  ): TypedContractMethod<
    [bountyId: BigNumberish, worker: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bounties"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, string, string] & {
        id: bigint;
        creator: string;
        ipfsCid: string;
        amount: bigint;
        status: bigint;
        assignedWorker: string;
        resultHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelBounty"
  ): TypedContractMethod<[bountyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createBounty"
  ): TypedContractMethod<[ipfsCid: string], [void], "payable">;
  getFunction(
    nameOrSignature: "submitResult"
  ): TypedContractMethod<
    [bountyId: BigNumberish, resultHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyAndRelease"
  ): TypedContractMethod<
    [bountyId: BigNumberish, success: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BidAccepted"
  ): TypedContractEvent<
    BidAcceptedEvent.InputTuple,
    BidAcceptedEvent.OutputTuple,
    BidAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "BountyCancelled"
  ): TypedContractEvent<
    BountyCancelledEvent.InputTuple,
    BountyCancelledEvent.OutputTuple,
    BountyCancelledEvent.OutputObject
  >;
  getEvent(
    key: "BountyCompleted"
  ): TypedContractEvent<
    BountyCompletedEvent.InputTuple,
    BountyCompletedEvent.OutputTuple,
    BountyCompletedEvent.OutputObject
  >;
  getEvent(
    key: "BountyCreated"
  ): TypedContractEvent<
    BountyCreatedEvent.InputTuple,
    BountyCreatedEvent.OutputTuple,
    BountyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ResultSubmitted"
  ): TypedContractEvent<
    ResultSubmittedEvent.InputTuple,
    ResultSubmittedEvent.OutputTuple,
    ResultSubmittedEvent.OutputObject
  >;

  filters: {
    "BidAccepted(uint256,address)": TypedContractEvent<
      BidAcceptedEvent.InputTuple,
      BidAcceptedEvent.OutputTuple,
      BidAcceptedEvent.OutputObject
    >;
    BidAccepted: TypedContractEvent<
      BidAcceptedEvent.InputTuple,
      BidAcceptedEvent.OutputTuple,
      BidAcceptedEvent.OutputObject
    >;

    "BountyCancelled(uint256)": TypedContractEvent<
      BountyCancelledEvent.InputTuple,
      BountyCancelledEvent.OutputTuple,
      BountyCancelledEvent.OutputObject
    >;
    BountyCancelled: TypedContractEvent<
      BountyCancelledEvent.InputTuple,
      BountyCancelledEvent.OutputTuple,
      BountyCancelledEvent.OutputObject
    >;

    "BountyCompleted(uint256,address,uint256)": TypedContractEvent<
      BountyCompletedEvent.InputTuple,
      BountyCompletedEvent.OutputTuple,
      BountyCompletedEvent.OutputObject
    >;
    BountyCompleted: TypedContractEvent<
      BountyCompletedEvent.InputTuple,
      BountyCompletedEvent.OutputTuple,
      BountyCompletedEvent.OutputObject
    >;

    "BountyCreated(uint256,address,uint256,string)": TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;
    BountyCreated: TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;

    "ResultSubmitted(uint256,string)": TypedContractEvent<
      ResultSubmittedEvent.InputTuple,
      ResultSubmittedEvent.OutputTuple,
      ResultSubmittedEvent.OutputObject
    >;
    ResultSubmitted: TypedContractEvent<
      ResultSubmittedEvent.InputTuple,
      ResultSubmittedEvent.OutputTuple,
      ResultSubmittedEvent.OutputObject
    >;
  };
}
