/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Decom } from "./Decom";
export * as factories from "./factories";
export { Decom__factory } from "./factories/Decom__factory";
